# This composite action bumps the npm and Github version to a new prerelease version. It returns the new version number.

name: 'Tag Prerelease Version'

inputs:
  version-type:
    description: "The type of version bump to make. One of: major, minor, patch, premajor, preminor, prepatch, or prerelease."
    required: true
  preid:
    description: "The prerelease identifier to use when bumping a prerelease version."
    required: true
    default: rc

outputs:
  results:
    description: "The name of the new prerelease version"
    value: ${{ steps.bump-prerelease.outputs.results }}

runs:
  using: "composite"
  steps:
    - name: Get version number
      id: agent-loader-version
      run: echo "results=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
      shell: bash
    - name: Bump prerelease version
      id: bump-prerelease
      run: |
        pattern=".*-rc\.[0-9]+$" \
        if [[ "${{ steps.agent-loader-version.outputs.results }}" =~ $pattern ]]; then \
          echo "results=$(npm version ${{ inputs.version-type }} --preid=${{ inputs.preid }})" >> $GITHUB_OUTPUT \
        else \
          echo "results=$(npm version prerelease" >> $GITHUB_OUTPUT \
        fi
      shell: bash
    - name: Add prerelease dist-tag
      id: add-prerelease-dist-tag
      run: npm dist-tag add rc@${{ steps.bump-prerelease.outputs.results }}
      shell: bash
