# This composite action bumps the npm and Github version to a new prerelease version. It returns the new version number.

name: 'Tag Prerelease Version'

inputs:
  version-type:
    description: "The type of version bump to make. One of: major, minor, patch, premajor, preminor, prepatch, or prerelease."
    required: true
  preid:
    description: "The prerelease identifier to use when bumping a prerelease version."
    required: true
    default: rc

outputs:
  results:
    description: "The name of the new prerelease version"
    value: ${{ steps.bump-prerelease.outputs.results }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.11.0 # See package.json for the stable node version that works with our testing.  Do not change this unless you know what you are doing as some node versions do not play nicely with our testing server.
    - name: Get version number
      id: agent-loader-version
      run: echo "results=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
    - name: Bump prerelease version
      id: bump-prerelease
      run: |
        if [[ "${{ steps.agent-loader-version.outputs.results }}" == *"-rc"* ]]; then
          echo "results=$(npm version ${{ inputs.version-type }} --preid=${{ inputs.preid }})" >> $GITHUB_OUTPUT
        else
          echo "results=$(npm version prerelease" >> $GITHUB_OUTPUT
        fi
    - name: Add prerelease dist-tag
      id: add-prerelease-dist-tag
      run: npm dist-tag add rc@${{ steps.bump-prerelease.outputs.results }}
