# This workflow is used to tag a new prerelease version

name: Tag Prerelease Version

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: "The type of version bump to make. One of: major, minor, patch, premajor, preminor, prepatch, or prerelease."
        type: string
        required: true
      preid:
        description: "The prerelease identifier to use when bumping a prerelease version."
        type: string
        required: true
        default: rc

jobs:
  tag-prerelease-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      NPM_TOKEN: ${{ secrets.BROWSER_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0 # See package.json for the stable node version that works with our testing.  Do not change this unless you know what you are doing as some node versions do not play nicely with our testing server.
      - name: Authenticate npm
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - name: Get version number
        id: agent-loader-version
        run: echo "results=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
      - name: Bump prerelease version
        id: bump-prerelease
        run: |
          pattern=".*-rc\.[0-9]+$"
          if [[ ${{ steps.agent-loader-version.outputs.results }} =~ $pattern ]]; then
            echo "results=$(npm version ${{ inputs.version-type }} --preid=${{ inputs.preid }})" >> $GITHUB_OUTPUT
          else
            echo "results=$(npm version prerelease)" >> $GITHUB_OUTPUT
          fi
      - name: Add prerelease dist-tag
        id: add-prerelease-dist-tag
        run: npm dist-tag add rc@${{ steps.bump-prerelease.outputs.results }}
